// <auto-generated />
namespace Vidya.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populateDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201703162201486_populateDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
